# Generated by Django 4.2.11 on 2024-05-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='orders_completed',
            field=models.IntegerField(default=0),
        ),
    ]
